default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: team_project_tracker_development

test:
  <<: *default
  database: team_project_tracker_test

production:
  adapter: postgresql
  encoding: unicode
  database: team_project_tracker_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432
